services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - dbdata:/var/opt/mssql
    ports:
      - "26:1433"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Server=db,1433;Database=Bank;User Id=sa;Password=P@ssword1;TrustServerCertificate=True;Encrypt=False;
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./Api/appsettings.json:/app/appsettings.json
volumes:
  dbdata: